################################################################################
#
# MODULAR_PSU_FIRMWARE
#
################################################################################

MODULAR_PSU_FIRMWARE_VERSION = 1.8.alpha2
MODULAR_PSU_FIRMWARE_SITE = https://github.com/eez-open/modular-psu-firmware.git
MODULAR_PSU_FIRMWARE_SITE_METHOD = git
MODULAR_PSU_FIRMWARE-SIMULATOR_LICENSE = BSD-2-Clause
MODULAR_PSU_FIRMWARE_INSTALL_STAGING = YES
MODULAR_PSU_FIRMWARE_CONF_OPTS += -DBUILD_STATIC_LIBS=ON

#SDL2_VERSION = 2.0.12
#SDL2_SOURCE = SDL2-$(SDL2_VERSION).tar.gz
#SDL2_SITE = http://www.libsdl.org/release
#SDL2_LICENSE = Zlib
#SDL2_LICENSE_FILES = COPYING.txt
#SDL2_INSTALL_STAGING = YES
#SDL2_CONFIG_SCRIPTS = sdl2-config

MODULAR_PSU_FIRMWARE_ENGINE_DEPENDENCIES += sdl2 sdl2_image sdl2_ttf libbsd bsd

MODULAR_PSU_FIRMWARE_DEPENDENCIES += libbsd
#MODULAR_PSU_FIRMWARE_DEPENDENCIES += bsd

MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(BR2_PACKAGE_SDL2),sdl2)
MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(BR2_PACKAGE_SDL2_IMAGE),sdl2_image)
MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(BR2_PACKAGE_SDL2_TTF),sdl2_ttf)
MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(SDL2),sdl2)

#MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(BR2_PACKAGE_bsd),bsd)
#MODULAR_PSU_FIRMWARE_DEPENDENCIES += $(if $(BR2_PACKAGE_libbsd),libbsd)

ifeq ($(BR2_TOOLCHAIN_HAS_THREADS),y)
MODULAR_PSU_FIRMWARE_CONF_OPTS += -DOPJ_USE_THREAD=ON
else
MODULAR_PSU_FIRMWARE_CONF_OPTS += -DOPJ_USE_THREAD=OFF
endif

$(eval $(cmake-package))
